### ISSUE TITLE
Does not build with 0.10 on VS2017

### ISSUE THREAD

**Issue by neilmendoza** [tado/ofxLiquidFun#6]
I get the following error if I try to build the examples on VS2017 with 0.10...

c:\dev\of_v0.10.0_vs2017_release\addons\ofxliquidfun\src\ofxbox2dutils.h(3): fatal error C1083: Cannot open include file: 'Box2D.h': No such file or directory (compiling source file src\ofApp.cpp)

Can't see anything super obvious so will use Linux for now.
